run:
  timeout: 5m
  go: '1.22'

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/menta2k/templater)
  
  gocyclo:
    min-complexity: 15
  
  cyclop:
    max-complexity: 15
  
  gocognit:
    min-complexity: 35
  
  nestif:
    min-complexity: 8
  
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  
  misspell:
    locale: US
  
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
  
  lll:
    line-length: 150
  
  gosec:
    excludes:
      - G306 # file permissions in tests
  
  forbidigo:
    forbid:
      - ^(print|println)$
    exclude-godoc-examples: true
  
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '0o755'
      - '0o644'

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - forcetypeassert
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - mnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - dupl
        - gosec
        - gocognit
        - cyclop
        - nestif
        - maintidx
        - tenv
        - staticcheck
        - gocritic
    - path: cmd/
      linters:
        - forbidigo
    - path: verify-deps\.go
      linters:
        - govet
        - unused
        - deadcode
    - text: "type assertion on error will fail on wrapped errors"
      linters:
        - errorlint
    - text: "possible nil pointer dereference"
      linters:
        - staticcheck
    - text: "elseif: can replace"
      linters:
        - gocritic
  
  max-issues-per-linter: 0
  max-same-issues: 0